const flightsData = [
  {
    flightNumber: "AI101",
    origin: "New Delhi",
    destination: "Mumbai",
    airline: "Air India",
    departureTime: "10:00 AM",
    arrivalTime: "12:30 PM",
    duration: "2h 30m",
    price: 5000,
  },
  {
    flightNumber: "6E202",
    origin: "Mumbai",
    destination: "Bangalore",
    airline: "IndiGo",
    departureTime: "03:00 PM",
    arrivalTime: "05:30 PM",
    duration: "2h 30m",
    price: 4500,
  },
  {
    flightNumber: "SG303",
    origin: "New Delhi",
    destination: "Chennai",
    airline: "SpiceJet",
    departureTime: "07:00 AM",
    arrivalTime: "10:30 AM",
    duration: "3h 30m",
    price: 5500,
  },
  {
    flightNumber: "AI404",
    origin: "Mumbai",
    destination: "New Delhi",
    airline: "Air India",
    departureTime: "06:00 PM",
    arrivalTime: "08:30 PM",
    duration: "2h 30m",
    price: 5200,
  },
  {
    flightNumber: "UK505",
    origin: "Bangalore",
    destination: "Hyderabad",
    airline: "Vistara",
    departureTime: "09:00 AM",
    arrivalTime: "10:15 AM",
    duration: "1h 15m",
    price: 3200,
  },
  {
    flightNumber: "AI606",
    origin: "Chennai",
    destination: "Kolkata",
    airline: "Air India",
    departureTime: "04:00 PM",
    arrivalTime: "06:30 PM",
    duration: "2h 30m",
    price: 4700,
  },
  {
    flightNumber: "6E707",
    origin: "Hyderabad",
    destination: "Delhi",
    airline: "IndiGo",
    departureTime: "01:00 PM",
    arrivalTime: "03:30 PM",
    duration: "2h 30m",
    price: 4800,
  },
  {
      flightNumber:"SG808", 
      origin:"Kolkata", 
      destination:"Mumbai", 
      airline:"SpiceJet", 
      departureTime:"11 AM", 
      arrivalTime:"01 PM", 
      duration:"2h", 
      price:"5000"
   },
   {
      flightNumber:"UK909", 
      origin:"New Delhi", 
      destination:"Pune", 
      airline:"Vistara", 
      departureTime:"08 AM", 
      arrivalTime:"10 AM", 
      duration:"2h", 
      price:"5300"
   },
   {
     flightNumber:"AI110", 
     origin:"Mumbai", 
     destination:"Kochi", 
     airline:"Air India", 
     departureTime:"07 PM", 
     arrivalTime:"09 PM", 
     duration:"2h", 
     price:"4500"
   },
   // Additional flights
   {
     flightNumber:"6E111", 
     origin:"Delhi", 
     destination:"Jaipur", 
     airline:"IndiGo", 
     departureTime:"09 AM", 
     arrivalTime:"10 AM", 
     duration:"1h", 
     price:"2500"
   },
   {
     flightNumber:"SG222", 
     origin:"Bangalore", 
     destination:"Goa", 
     airline:"SpiceJet", 
     departureTime:"12 PM", 
     arrivalTime:"01 PM", 
     duration:"1h", 
     price:"3000"
   },
   {
     flightNumber:"UK333", 
     origin:"Hyderabad", 
     destination:"Chennai", 
     airline:"Vistara", 
     departureTime:"03 PM", 
     arrivalTime:"04 PM", 
     duration:"1h", 
     price:"2800"
   },
   {
     flightNumber:"AI444", 
     origin:"Kolkata", 
     destination:"Delhi", 
     airline:"Air India", 
     departureTime:"05 PM", 
     arrivalTime:"07 PM", 
     duration:"2h" ,  
     price : '4000'  
   },
   {
      flightNumber : '6E555',  
      origin : 'Pune',  
      destination : 'Mumbai',  
      airline : 'IndiGo',  
      departureTime : '08 AM',  
      arrivalTime : '09 AM',  
      duration : '1h',  
      price : '1500'  
   },
   {
      flightNumber : 'SG666',  
      origin : 'Delhi',  
      destination : 'Bhopal',  
      airline : 'SpiceJet',  
      departureTime : '11 AM',  
      arrivalTime : '12 PM',  
      duration : '1h' ,  
      price :"2700"  
   },
   {
       flightNumber : 'UK777',  
       origin : 'Chennai',  
       destination : 'Coimbatore',  
       airline : 'Vistara',  
       departureTime : '02 PM',  
       arrivalTime : '03 PM',  
       duration : '1h',  
       price : '2000'  
   },
   {
       flightNumber : 'AI888',  
       origin : 'Kolkata',  
       destination : 'Lucknow',  
       airline : 'Air India',  
       departureTime : '04 PM',  
       arrivalTime : '06 PM',  
       duration : '2h',  
       price : '3400'  
   },
   {
       flightNumber : '6E999',   
       origin : 'Hyderabad',   
       destination : 'Ahmedabad',   
       airline : 'IndiGo',   
       departureTime : '06 AM',   
       arrivalTime : '08 AM',   
       duration : '2h' ,   
       price : '3600'   
   },
   // More flights
   {
       flightNumber:'AI1001',
       origin:'Delhi',
       destination:'Varanasi',
       airline:'Air India',
       departureTime:'05 AM',
       arrivalTime:'07 AM',
       duration:'2h',
       price:'3200'
   },
   {
       flightNumber:'6E1002',
       origin:'Bangalore',
       destination:'Mangalore',
       airline:'IndiGo',
       departureTime:'11 AM',
       arrivalTime:'12 PM',
       duration:'1h',
       price:'2000'
   },
   {
       flightNumber:'SG1003',
       origin:'Chennai',
       destination:'Madurai',
       airline:'SpiceJet',
       departureTime:'03 PM',
       arrivalTime:'04 PM',
       duration:'1h',
       price:'2200'
   },
   {
        flightNumber:'UK1004',
        origin:'Kolkata',
        destination:'Raipur',
        airline:'Vistara',
        departureTime:'02 PM',
        arrivalTime:'04 PM',
        duration:'2h',
        price:'2900'
   },
   {
        flightNumber:'AI1005',
        origin:'Hyderabad',
        destination:'Visakhapatnam',
        airline:'Air India',
        departureTime:'08 AM',
        arrivalTime:'09 AM',
        duration:'1h',
        price:'2500'
   },
   {
        flightNumber:'6E1006',
        origin:'Pune',
        destination:'Nagpur',
        airline:'IndiGo',
        departureTime:'01 PM',
        arrivalTime:'02 PM',
        duration:'1h',
        price:'1800'
   },
   {
         flightNumber :'SG1007' ,    
         origin :'Delhi' ,    
         destination :'Amritsar' ,    
         airline :'SpiceJet' ,    
         departureTime :'09 AM' ,    
         arrivalTime :'10 AM' ,    
         duration :'1h' ,    
         price :'2300'   
   },
   {
         flightNumber :'UK1008' ,    
         origin :'Chennai' ,    
         destination :'Tirupati' ,    
         airline :'Vistara' ,    
         departureTime :'11 AM' ,    
         arrivalTime :'12 PM' ,    
         duration :'1h' ,    
         price :'2100'   
   },

   //international
   
    {
      flightNumber: "AI3001",
      origin: "New Delhi",
      destination: "London",
      airline: "Air India",
      departureTime: "11:30 PM",
      arrivalTime: "05:30 AM",
      duration: "9h 30m",
      price: 55000,
    },
    {
      flightNumber: "6E3002",
      origin: "Mumbai",
      destination: "Dubai",
      airline: "IndiGo",
      departureTime: "02:00 AM",
      arrivalTime: "04:30 AM",
      duration: "3h 30m",
      price: 15000,
    },
    {
      flightNumber: "SG3003",
      origin: "Bangalore",
      destination: "Singapore",
      airline: "SpiceJet",
      departureTime: "10:15 PM",
      arrivalTime: "06:00 AM",
      duration: "8h 15m",
      price: 42000,
    },
    {
      flightNumber: "UK3004",
      origin: "Hyderabad",
      destination: "Bangkok",
      airline: "Vistara",
      departureTime: "09:45 PM",
      arrivalTime: "05:15 AM",
      duration: "7h 30m",
      price: 38000,
    },
    {
      flightNumber: "AI3005",
      origin: "Chennai",
      destination: "Tokyo",
      airline: "Air India",
      departureTime: "01:00 AM",
      arrivalTime: "10:30 AM",
      duration: "8h 30m",
      price: 60000,
    },
    {
      flightNumber: "6E3006",
      origin: "Kolkata",
      destination: "Doha",
      airline: "IndiGo",
      departureTime: "11:00 PM",
      arrivalTime: "01:30 AM",
      duration: "4h 30m",
      price: 22000,
    },
    {
        flightNumber:"SG3007", 
        origin:"Delhi", 
        destination:"New York", 
        airline:"SpiceJet", 
        departureTime:"08 PM", 
        arrivalTime:"06 AM", 
        duration:"14h", 
        price:"85000"
     },
     {
        flightNumber:"UK3008", 
        origin:"Mumbai", 
        destination:"Toronto", 
        airline:"Vistara", 
        departureTime:"10 PM", 
        arrivalTime:"07 AM", 
        duration:"15h", 
        price:"90000"
     },
     {
       flightNumber:"AI3009", 
       origin:"Bangalore", 
       destination:"Sydney", 
       airline:"Air India", 
       departureTime:"04 PM", 
       arrivalTime:"06 AM", 
       duration:"13h", 
       price:"75000"
     },
     {
       flightNumber:"6E3010", 
       origin:"Hyderabad", 
       destination:"Kuala Lumpur", 
       airline:"IndiGo", 
       departureTime:"12 PM", 
       arrivalTime:"07 PM", 
       duration:"5h 30m", 
       price:"20000"
     },
     // Additional unique international flights
     {
       flightNumber:"SG3011", 
       origin:"Delhi", 
       destination:"Frankfurt", 
       airline:"SpiceJet", 
       departureTime:"11 PM", 
       arrivalTime:"05 AM", 
       duration:"8h",  
       price :"65000"  
     },
     {
         flightNumber:'UK3012',
         origin:'Mumbai',
         destination:'Amsterdam',
         airline:'Vistara',
         departureTime:'09 PM',
         arrivalTime:'05 AM',
         duration:'9h',
         price:'70000'
     },
     {
         flightNumber:'AI3013',
         origin:'Chennai',
         destination:'Los Angeles',
         airline:'Air India',
         departureTime:'07 PM',
         arrivalTime:'06 PM',
         duration:'16h',
         price:'95000'
     },
     {
         flightNumber:'6E3014',
         origin:'Bangalore',
         destination:'Hong Kong',
         airline:'IndiGo',
         departureTime:'03 PM',
         arrivalTime:'09 PM',
         duration:'5h 30m',
         price:'25000'
     },
     {
          flightNumber:'SG3015',  
          origin:'Kolkata',  
          destination:'Dubai',  
          airline:'SpiceJet',  
          departureTime:'10 AM',  
          arrivalTime:'12 PM',  
          duration:'4h' ,  
          price :'18000'  
     },
     {
          flightNumber:'UK3016',  
          origin:'Delhi',  
          destination:'San Francisco',  
          airline:'Vistara',  
          departureTime:'08 PM',  
          arrivalTime:'07 AM',  
          duration:'16h' ,  
          price :'90000'   
     },
     {
           flightNumber :'AI3017' ,    
           origin :'Mumbai' ,    
           destination :'Zurich' ,    
           airline :'Air India' ,    
           departureTime :'11 AM' ,    
           arrivalTime :'05 PM' ,    
           duration :'10h' ,    
           price :'80000'   
     },
     {
      flightNumber: "AI4001",
      origin: "New Delhi",
      destination: "Bangkok",
      airline: "Air India",
      departureTime: "01:00 AM",
      arrivalTime: "07:00 AM",
      duration: "5h",
      price: 22000,
    },
    {
      flightNumber: "AI4002",
      origin: "Mumbai",
      destination: "Dubai",
      airline: "Air India",
      departureTime: "03:00 AM",
      arrivalTime: "05:30 AM",
      duration: "3h 30m",
      price: 15000,
    },
    {
      flightNumber: "AI4003",
      origin: "Bengaluru",
      destination: "Singapore",
      airline: "Air India",
      departureTime: "08:15 PM",
      arrivalTime: "04:00 AM",
      duration: "8h 15m",
      price: 42000,
    },
    {
      flightNumber: "IX4004",
      origin: "Tiruchirappalli",
      destination: "Dammam",
      airline: "Air India Express",
      departureTime: "11:30 PM",
      arrivalTime: "03:00 AM",
      duration: "4h 30m",
      price: 18000,
    },
    {
      flightNumber: "6E4005",
      origin: "Delhi",
      destination: "Doha",
      airline: "IndiGo",
      departureTime: "02:30 AM",
      arrivalTime: "04:30 AM",
      duration: "3h",
      price: 12000,
    },
    {
      flightNumber: "UK4006",
      origin: "Mumbai",
      destination: "London (Heathrow)",
      airline: "Vistara",
      departureTime: "10 PM",
      arrivalTime: "06 AM (next day)",
      duration: "9h 30m",
      price: 75000,
    },
    {
        flightNumber:"SG4007", 
        origin:"Bangalore", 
        destination:"Kuala Lumpur", 
        airline:"SpiceJet", 
        departureTime:"05 PM", 
        arrivalTime:"10 PM", 
        duration:"5h" ,  
        price :"25000"  
     },
     {
        flightNumber:"AI4008", 
        origin:"Delhi", 
        destination:"Frankfurt", 
        airline:"Air India", 
        departureTime:"11 PM", 
        arrivalTime:"05 AM (next day)", 
        duration:"8h" ,  
        price :"65000"  
     },
     {
       flightNumber:"6E4009", 
       origin:"Hyderabad", 
       destination:"Muscat", 
       airline:"IndiGo", 
       departureTime:"09 PM", 
       arrivalTime:"10 PM", 
       duration:"1h" ,  
       price :"10000"  
     },
     {
       flightNumber:"IX4010", 
       origin:"Chennai", 
       destination:"Jeddah", 
       airline:"Air India Express", 
       departureTime:"12 AM", 
       arrivalTime:"03 AM", 
       duration:"4h" ,  
       price :"15000"  
     },
     // Additional unique international flights
     {
       flightNumber:"SG4011", 
       origin:"Delhi", 
       destination:"Los Angeles", 
       airline:"SpiceJet", 
       departureTime:"08 PM", 
       arrivalTime:"07 AM (next day)", 
       duration:"16h" ,  
       price :"90000"  
     },
     {
         flightNumber:'UK4012',
         origin:'Mumbai',
         destination:'Toronto',
         airline:'Vistara',
         departureTime:'10 PM',
         arrivalTime:'07 AM (next day)',
         duration:'15h',
         price:'85000'
     },
     {
         flightNumber:'AI4013',
         origin:'Bengaluru',
         destination:'Sydney',
         airline:'Air India',
         departureTime:'04 PM',
         arrivalTime:'06 AM (next day)',
         duration:'13h',
         price:'80000'
     },
     {
         flightNumber:'6E4014',
         origin:'Hyderabad',
         destination:'Bangkok',
         airline:'IndiGo',
         departureTime:'11 AM',
         arrivalTime:'05 PM',
         duration:'5h',  
         price :'20000'   
     },
     {
          flightNumber :'IX4015' ,    
          origin :'Delhi' ,    
          destination :'Abu Dhabi' ,    
          airline :'Air India Express' ,    
          departureTime :'09 PM' ,    
          arrivalTime :'11 PM' ,    
          duration :'3h' ,    
          price :'12000'   
     },
     {
           flightNumber :'SG4016' ,    
           origin :'Mumbai' ,    
           destination :'Istanbul' ,    
           airline :'SpiceJet' ,    
           departureTime :'11 PM' ,    
           arrivalTime :'06 AM (next day)' ,    
           duration :'8h' ,    
           price :'70000'   
     }
  
  
  
];

export default flightsData;
